groups:
  - name: CPUThreshold
    rules:
      - alert: HighCPUUsage
        expr: job:cpu_usage:avg1m > 50
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage on {{ $labels.instance }} is greater than 50%. Current usage: {{ $value }}%"

      - alert: CriticalCPUUsage
        expr: job:cpu_usage:avg1m > 90
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Critical CPU usage on {{ $labels.instance }}"
          description: "CPU usage on {{ $labels.instance }} is greater than 90%. Current usage: {{ $value }}%"
