global:
  scrape_interval: 15s
  evaluation_interval: 10s
rule_files:
  - cpu_rules.yml
  - mem_rules.yml
  - cpu_recording_rules.yml
  - mem_recording_rules.yml
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['localhost:8080']
