{
 "title": "Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers CPU (each %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",name=~\".+\"}[1m])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Memory (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers Memory (each GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{job=\"cadvisor\",name=~\".+\"}) by (name) / (1024 * 1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Storage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "100 * (1 - (node_filesystem_free_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Logs - Gateway",
   "type": "logs",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{filename=\"/var/lib/docker/containers/5abc1baa08b8c30670790d1386fb2fc97cd540bd48569c9386cc02e73029ef10/5abc1baa08b8c30670790d1386fb2fc97cd540bd48569c9386cc02e73029ef10-json.log\"} |= ``"
    }
   ]
  },
  {
   "title": "Logs - Auth",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "{filename=\"/var/lib/docker/containers/d3ad12a3e52b170283b99099aac1d63a9c39ae4514160119094124a8e14ef8b2/d3ad12a3e52b170283b99099aac1d63a9c39ae4514160119094124a8e14ef8b2-json.log\"} |= ``"
    }
   ]
  },
  {
   "title": "Logs - Game",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "{filename=\"/var/lib/docker/containers/51303451b6f6fa36159ff706ced6cdc8ccd94803695410e6b841114643134847/51303451b6f6fa36159ff706ced6cdc8ccd94803695410e6b841114643134847-json.log\"} |= ``"
    }
   ]
  },
  {
   "title": "Logs - Package",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "{filename=\"/var/lib/docker/containers/2029fd12550cd85aaaf0b6220fc4fbf4bede9d30d9f42b1dc68930e5e375a18b/2029fd12550cd85aaaf0b6220fc4fbf4bede9d30d9f42b1dc68930e5e375a18b-json.log\"} |= ``"
    }
   ]
  }
 ]
}