version: "3.8"

services:
  prometheus: # default port 9090
    image: prom/prometheus:v2.18.1
    container_name: do-prometheus
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./conf/prometheus/cpu_recording_rules.yml:/etc/prometheus/cpu_recording_rules.yml
      - ./conf/prometheus/mem_rules.yml:/etc/prometheus/mem_rules.yml
      - ./conf/prometheus/cpu_rules.yml:/etc/prometheus/cpu_rules.yml
      - ./conf/prometheus/mem_recording_rules.yml:/etc/prometheus/mem_recording_rules.yml
    user: root
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/data/prometheus"

  node-exporter: # Sharing Host network, default port 9100
    image: prom/node-exporter:v1.8.1
    container_name: do-node-exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"
  # cadvisor: # google/cadvisor is deprecated, use gcr.io/cadvisor/cadvisor
  #   image: gcr.io/cadvisor/cadvisor:v0.49.1
  #   container_name: do-cadvisor
  #   restart: unless-stopped
  #   network_mode: host
  #   volumes:
  #   - /:/rootfs:ro
  #   - /var/run:/var/run:rw
  #   - /sys:/sys:ro
  #   - /var/lib/docker/:/var/lib/docker:ro
  #   depends_on:
  #   - redis
  grafana:
    image: grafana/grafana-oss:11.1.0
    container_name: do-grafana
    restart: unless-stopped
    network_mode: host # 추가
    volumes:
      - ./conf/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./conf/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./conf/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./conf/grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json
      - ./data/grafana:/var/lib/grafana
    user: root

  # redis:
  #   image: redis:latest
  #   container_name: do-redis
  #   command: redis-server /usr/local/etc/redis/redis.conf
  #   restart: unless-stopped
  #   ports:
  #   - 6390:6379
  #   volumes:
  #   - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
  #   - ./data/redis:/data
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 256M
